# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Yaml Lint"

on: # yamllint disable-line rule:truthy
    push:
        paths:
            - "**.yml"
            - "**.yaml"
    pull_request:
        paths:
            - "**.yml"
            - "**.yaml"

permissions:
  contents: read

jobs:
    yaml-lint:
        name: "Yaml lint"

        runs-on: "ubuntu-latest"

        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
              with:
                egress-policy: audit

            - name: "Git checkout"
              uses: "actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5" # v2.7.0
              with:
                  fetch-depth: 2
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Lint YAML files"
              uses: "ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c" # v3.1.1
              with:
                  config_file: ".yamllint.yaml"
                  file_or_dir: "."
                  strict: true
